name: Multiple jobs
'on': workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Buld the App
        run: echo "App bnn raha hai"
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Test ho raha hai app"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "app deply ho raha raha"
