name: Jaadu
on: workflow_dispatch
jobs:
  web:
    runs-on: ubuntu-latest
   steps:
   - name: Checkout the code
     uses: actions/checkout@v4
   - name: Print the web index.html
     run: cat index.html
